### ISSUE TITLE
Get referents

### ISSUE THREAD

**Issue by ludehon** [johnwmillr/LyricsGenius#100]
**Handle song's referents in order to get annotations id**
Referents are the sections of a piece of content to which annotations are attached. Each referent is associated with a web page or a song and may have one or more annotations. Referents can be searched by the document they are attached to or by the user that created them : [referents](https://docs.genius.com/#referents-h2)

- To get referents : referents?song_id=id

- From the returned JSON we have array of referents in ["response"]["referents"]

- From a referent we have annotations id in ["annotations"][annotation_indice]["id"]

We can build a list of annotations id and use it for [Genius.get_annotation(id_)](https://github.com/johnwmillr/LyricsGenius/blob/49f7d573efad5d1a633a73480b2a99d50c237b60/lyricsgenius/api.py#L104)

I hope this makes sense, I can help but I'm not familiar with GitHub collaboration atm.

**Comment by johnwmillr** [comment]
Thanks for suggesting this, @ludehon. The `get_referents` method you added in `api.py` looks like it could work. Feel free to open a pull request from your forked repo.

**Comment by ludehon** [comment]
Ok I will continue some work around annotations and open a pull request. 
But I have some kind of noob problem : I never used the syntax package.class (lyricsgenius.api) and my Python 3.7 gives me 

> ModuleNotFoundError: No module named 'lyricsgenius'

I have the __init__.py file in the folder... The only way I found to make the relative import works is to remove "lyricsgenius." before the file name. Do you have an idea ? I didn't find solutions yet...
