### ISSUE TITLE
Question how to access artist.songs

### ISSUE THREAD

**Issue by ragrets** [johnwmillr/LyricsGenius#120]
```
import lyricsgenius as genius

api = genius.Genius(geniusCreds)    
artist = api.search_artist(artist_name, max_songs=2)
song_list = artist.songs
print(song_list)

songs = []
x = 0
while x < len(song_list):
    songs.append(f"{x + 1}: {(song_list)[x]}")
    x = x+1
print(songs)
```

Am I missing something? I initially printed `song_list` to see its content

```
[('I Miss You', '\u200b\u200bblink-182'), ('What’s My Age Again?', '\u200b\u200bblink-182')]
```
but I don't see where the 2nd print got the lyrics

```
[
    '1: "I Miss You" by \u200b\u200bblink-182:\n    [Intro: Mark Hoppus]\n    I miss you, I miss you\n    \n    
        [Verse 1: Mark Hoppus]\n    Hello there\n    The angel from my ni...', 
    '2: "What’s My Age Again?" by \u200b\u200bblink-182:\n    [Verse 1: Mark Hoppus]\n    I took her out\n    
        It was a Friday night\n    I wore cologne\n    To get the feeling right\n    ...'
    ]
```
Also, I get "Song object is not subscriptable" when i try to access the song names by: 
```
x = 0
while x < len(song_list):
    songs.append(f"{x + 1}: {(song_list)[x][0]}")
    x = x+1
```

**Comment by johnwmillr** [comment]
I'm not quite sure what you're trying to accomplish. Do you want the `songs` variable to be a list of all of the lyrics?

In your `songs.append(f"{x + 1}: {(song_list)[x][0]}")` line, you are asking for the string representation of the Song class, so you're calling its [`__str__`](https://github.com/johnwmillr/LyricsGenius/blob/85de3007e54db08a9e6557b062eb3e68615fe550/lyricsgenius/song.py#L205-L212) method, which includes a snippet of the song's lyrics.

If you want just the song lyrics, try something like this:

```python
x = 0
while x < len(song_list):
    songs.append(f"{x + 1}: {(song_list)[x].lyrics}")
    x = x + 1
print(songs)
```

Does that address your question?

**Comment by johnwmillr** [comment]
Closing this issue, as I believe the above code will fix the problem. Feel free to comment again or open a new issue if necessary.
