### ISSUE TITLE
Possible to search by tags

### ISSUE THREAD

**Issue by saebod** [johnwmillr/LyricsGenius#127]
Hi,
is there a way to make the script to search by tags?

What i'm looking for is to find danish songs made in specific years

so i would love if it were possible to search by the tag 'denmark'
ex: https://genius.com/tags/danmark/all
and then filter the tag 'denmark' for year 'X'.

**Comment by Allerter** [comment]
There is a way to do that, but since it concerns web-scraping, I don't think LyricsGenius would implement that in the future. Nonetheless, you can do it yourself. Take a look at the response I sent to a similar issue (#149)
