### ISSUE TITLE
Lyrics are in french

### ISSUE THREAD

**Issue by 1meekay** [johnwmillr/LyricsGenius#136]
Using `genius.search_song('renegade ft. eminem', 'jay z')` returned the lyrics in French. Granted, `genius.search_song('renegade', 'jay z')` returns the same song but with English lyrics but I'm just curious why adding a featured artist returned the lyrics in French.

**Comment by Allerter** [comment]
That's because the top result for searching  "jay z renegade ft. eminem" is the French translation of the song.
