### ISSUE TITLE
Genius API returns non-songs masquerading as songs

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#14]
The Genius API includes entries the site refers to as songs that aren't actually songs.

For example, [searching for Taylor Swift](https://genius.com/search?q=taylor%20swift%201989) will return entries for [liner notes](https://genius.com/Taylor-swift-1989-liner-notes-annotated) and a [booklet](https://genius.com/Taylor-swift-1989-booklet-annotated) along with actual song lyrics.

My wrapper needs to be able to identify and reject these non-song entries. From what I can tell, the Genius API does not flag these items as non-songs — their type is still listed as "song" in the JSON object.

**Comment by michael-erasmus** [comment]
Hey there, I was looking for a way to collect lyrics data in Python and came across your project, nice work! I wanted to download the lyrics to all the songs from The Beatles and also ran into this issue, quite a few of the 'songs' are actually album tracklistings, 

Perhaps you could use a set of heuristics to filter them out, like if the title contains the words `[Booklet]` or `Tracklist`?

**Comment by johnwmillr** [comment]
I'm glad you've found the package to be of some use! I've wanted to fix this issue for awhile but haven't made the time to work on it. I think a heuristic approach like you've described is a good place to start. I'm not sure how else to approach the issue. I really wish Genius flagged non-songs as such, but alas, no luck. 

You're more than welcome to open a PR if you come up with a solution. Otherwise, I'll try to address the issue in the next week or so. Ultimately I'd want to give the user a boolean flag to choose whether or not they'd like to filter out these non-songs.

**Comment by johnwmillr** [comment]
I just opened PR #39 to address this issue. I've added a simple regex to catch some of the offending phrases. The implementation is a little messy, but, for now, it should help clean up the songs that are returned.

**Comment by johnwmillr** [comment]
The detection of non-songs can certainly be improved in the future, but I'll consider the issue closed for now.

**Comment by johnwmillr** [comment]
Great! Thanks for the encouragement to finally get around to addressing this issue...
