### ISSUE TITLE
getting "Specified song does not have a valid URL with lyrics. Rejecting." error

### ISSUE THREAD

**Issue by chethan25** [johnwmillr/LyricsGenius#140]
I am getting "Specified song does not have a valid URL with lyrics. Rejecting." error while searching a song but it works after a few more tries for the same song, I am not sure what's causing this issue. I'm making a reddit bot using this package and i'm not able to come up with a working logic to retry the search without messing up other part of my code.
![Screenshot from 2020-05-20 20-42-34](https://user-images.githubusercontent.com/59925098/82463679-bcd75c80-9ada-11ea-8dea-2c39772ab2c8.png)

**Comment by Allerter** [comment]
#139 This is probably because of Genius's new theme. Try the solution I provided there, and see if the issue persists.

**Comment by chethan25** [comment]
your solution works, haven't got that error since i replaced those lines with your code. thanks a lot.

**Comment by johnwmillr** [comment]
Thank you for all your help on these issues, @Allerter. You're more than welcome to put a PR together that addresses some of these bugs you've solved.

**Comment by Allerter** [comment]
> Thank you for all your help on these issues, @Allerter. You're more than welcome to put a PR together that addresses some of these bugs you've solved.

It's my pleasure. Actually it was just one bug, and since it's only about 10 lines of code I thought it wouldn't be necessary. But sure, I'll submit a pull request soon.
