### ISSUE TITLE
Get URL of song page

### ISSUE THREAD

**Issue by BirdLeaflol** [johnwmillr/LyricsGenius#141]
Would it be possible to add a feature that allows me to get the URL of a song page, or if this already exists, could you tell me how to do it?

**Comment by Allerter** [comment]
If I've understood your question correctly, the URL of each song is in its JSON file, can be accessed through `song.url` after a song is fetched.
If you want to read the URLs of an artist you've saved:
```
with open('lyrics.json','r') as f:
    data = json.load(f)
for song in data['songs']:
    print(song['url'])
```
I suggest using the tree viewer service like [Code Beautify](https://codebeautify.org/) to see what info the saved JSON file holds.
