### ISSUE TITLE
Incomplete lyrics provided

### ISSUE THREAD

**Issue by Qaahir** [johnwmillr/LyricsGenius#144]
**Problem Description**
I'm running a personal project to determine lyrical trends in popular rap songs over the years. Using a function with your package, I've run over the dataframe containing track & artist names to populate the third column with their respective lyrics. 

However, the resultant strings cut off at around 120 characters, followed by an ellipsis to indicate incompleteness. 

Initially I thought there may be an issue when using the package in a pandas dataframe, but I got the same result when saving the lyrics to text files.

Is there a specific setting/option I've missed that allows me to extract the full lyric text? I haven't been able to find the solution elsewhere.

**Example Result**
Copied directly from a saved text file:
_"Holy Grail" by JAY-Z:
    [Intro: Justin Timberlake]
    You'd take the clothes off my back and I'd let you
    You'd steal the food r..._

**Version info**
 - Package version 1.8.6
 - Windows 10 running Python 3.7 in Spyder & Jupyter Notebook

**Comment by johnwmillr** [comment]
How are you attempting to save the lyrics?

You should use the `save_lyrics` method on either a `Song` or `Artist` object.

**Comment by Qaahir** [comment]
That did it... Seems I tried to cut a few corners in my coding, but at least the initial issue is resolved. Thanks!
