### ISSUE TITLE
Save song data in different json files.

### ISSUE THREAD

**Issue by chethan25** [johnwmillr/LyricsGenius#150]
Feature to save all of artist's songs to different json files instead of one file would greatly help my project.

**Comment by Allerter** [comment]
Since the artist's songs are all already available using the `artist.songs` attribute, you could easily do this yourself:
```python
# suppose we have an artist object
for song in artist.songs:
    song.save_lyrics()
```

**Comment by chethan25** [comment]
This works but I was getting timeout error so I put the code in try block and sleep for 5 min if there's an exception. thanks for the help.
