### ISSUE TITLE
Inconsistent use of '\n\n' in lyrics. 

### ISSUE THREAD

**Issue by chethan25** [johnwmillr/LyricsGenius#163]
In lyrics '\n\n' is used to separate sections of a song but it's very inconsistent (only one '\n' is present). I've to manually add one more '\n' character to the json file. Is there any way to resolve this issue?

for eg - \n\n[Verse 4: Buddah Bless]\nAiyo, it's time to get drastic, but God bless the fantastic\nHerb passed it, now I melt the mic like it's plastic\nI rag crews 'cause I'm bad news\nIn a mad mood, I'm servin' brothers quicker than fast food\nStep to this and get your body blown\n'Cause I'm no maric\u00f3n, for poems I slide the hotties home\nHere's some advice, I'm mad nice\nAiyo, I'm quick to lick the mag twice and cold take a f*g's life\nMy swellin' melon got ni*gas jealin'\nAiyo, fu*k bribes, I'm takin' ni*gas lives like a felon\n[Verse 5: Big Twan]\nYo, I'm bustin' chumps like a Glock 10

There should be two '\n' characters before verse 5 but there's only one.

**Comment by Allerter** [comment]
Hey, thanks for bringing up this issue. Before we proceed, I need some information to recreate your issue here:

- Your LyricsGenius version
- The songs you have noticed that lack the `\n\n`, as you mentioned that it's __very__ inconsistent.
- A minimal working script to reproduce the issue.

I just tried this:
```python
genius = Genius(token)
lyrics = genius.lyrics('https://genius.com/Big-l-8-iz-enuff-lyrics')
```
and all the '\n\n's  were present for me.

**Comment by chethan25** [comment]
The \n\n s are consistent in the latest version. I was on 1.8.6 when I saved the json files.

I also would like to appreciate this package, it has greatly helped my project. [I made a reddit bot that replies with song lyrics and metadata.](https://github.com/chethan25/rapgeniusbot)
