### ISSUE TITLE
Artist is missing from Song.to_dict

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#166]
https://github.com/johnwmillr/LyricsGenius/blob/a0595147727a9e1932b0fec0f8529b9956bdbcf1/lyricsgenius/song.py#L162-L166

`artist` should be exported along with the other `Song` fields.

**Comment by Allerter** [comment]
In #162, all we would need to do is this:
```python
def to_dict(self):
    body = super().to_dict()
    body['artist'] = self.artist
    body['lyrics'] = self.lyrics
    return body
```

**Comment by johnwmillr** [comment]
Perfect!
