### ISSUE TITLE
The Doc is supposed to UPDATE

### ISSUE THREAD

**Issue by Xpectuer** [johnwmillr/LyricsGenius#167]
In documentation https://lyricsgenius.readthedocs.io/en/master/examples/snippets.html#all-the-songs-of-an-artist
```python
from lyricsgenius import Genius

genius = Genius(token)
genius.search_artist('Andy Shauf')
artist.save_lyrics()
```
should be updated as
```python
from lyricsgenius import Genius

genius = Genius(token)
artist = genius.search_artist('Andy Shauf')
artist.save_lyrics()
```

Best wishes~

**Comment by Allerter** [comment]
Hi. Thanks for reporting this. If you're interested, you could open a PR with the update.
