### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by smorello87** [johnwmillr/LyricsGenius#175]
**Describe the bug**
When I try to run the script as per the documentation (e.g. 

export GENIUS_CLIENT_ACCESS_TOKEN="MYTOKENGOESHERE" 
python3 -m lyricsgenius artist "The Beatles" --max-songs 5 --save ) I received the following error:

Traceback (most recent call last):
  File "/Users/veritas44/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/veritas44/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/veritas44/opt/anaconda3/lib/python3.8/site-packages/lyricsgenius/__main__.py", line 8, in <module>
    from lyricsgenius.api import Genius
ImportError: cannot import name 'Genius' from 'lyricsgenius.api' (/Users/veritas44/opt/anaconda3/lib/python3.8/site-packages/lyricsgenius/api/__init__.py)

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. Install the LyricsGenius package
2. Run the script

Include the error message associated with the bug.

**Version info**
 - Package version 2.0.2
 - OS: [macOS Catalina]
 - Python/Anaconda 3.8

**Comment by Allerter** [comment]
Use the master branch until version 3.0 is released.
```bash
pip uninstall lyricsgenius
pip install git+https://github.com/johnwmillr/LyricsGenius.git
```

**Comment by smorello87** [comment]
Thank you, that fixed it.
