### ISSUE TITLE
No git tag on v3.0

### ISSUE THREAD

**Issue by Allerter** [johnwmillr/LyricsGenius#177]
V3.0 is released on pip, but there is not git tag associated with it - more importantly not one on the [tags page](https://github.com/johnwmillr/LyricsGenius/tags). So I can't add a Release on GitHub for it. @johnwmillr, could you please add the `3.0.0` tag for the latest commit?

**Comment by johnwmillr** [comment]
Sure thing, added the `3.0.0` tag [here](https://github.com/johnwmillr/LyricsGenius/releases/tag/3.0.0).
