### ISSUE TITLE
Request: Support reading token from file when using command line

### ISSUE THREAD

**Issue by AndydeCleyre** [johnwmillr/LyricsGenius#197]
**Is your feature request related to a problem? Please describe.**
I would like to provide the token via a file, without exposing the credential as an environment variable (or as part of the command), to better manage security.

**Describe the solution you'd like**
When using the CLI:
- If `GENIUS_ACCESS_TOKEN` in environment, use that
- Otherwise, check file `${XDG_CONFIG_HOME:-~/.config}/LyricsGenius/access_token` or similar

**Describe alternatives you've considered**
I can use a shell file and source that, but the credential will still be exposed as an environment variable.

**Comment by allerter** [comment]
Although this would be a nice utility to have, you don't really need LyricsGenius to do this. You can easily use Python's standard library [configparser](https://docs.python.org/3/library/configparser.html) to parse your config file and extract your token. We'd just do the same if we added this option to LyricsGenius.

**Comment by AndydeCleyre** [comment]
To be clear, this request is regarding use of the CLI.

**Comment by allerter** [comment]
In the case of the CLI, we could add alternate paths to check for a token as I've seen other projects do that.

**Comment by allerter** [comment]
But is the token any safe in a file rather than as an environment variable? It seems that an env var might be the safest option.

**Comment by allerter** [comment]
I'm closing this issue as it seems to be solved. Feel free to comment here if you have anything else to add.
