### ISSUE TITLE
Remove the Hyperlink text from lyrics scrapper

### ISSUE THREAD

**Issue by bdubs1991** [johnwmillr/LyricsGenius#218]
When you use your package to scrape lyrics it includes text for the hyperlinks at the end of the lyrics, see attached screenshot. For a reproductible example, I have attached this in a jupyter notebook.
![image](https://user-images.githubusercontent.com/36580462/129431623-1107c95c-2e0f-4832-843d-7153a4a43b8f.png). This can be removed with some regex code I have created below. I am agnostic if this should be done to all lyrics or only when remove_section_headers=True is selected.

Potential Solution:
hyperlinks_removed = re.sub(r"[0-9]+EmbedShare URLCopyEmbedCopy",'',lyrics) 

Example for reproduction

import lyricsgenius as lg
import genius_token as gt
genius = lg.Genius(gt.token,  # Client access token from Genius Client API page
                             skip_non_songs=True, excluded_terms=["(Remix)", "(Live)"],
                             remove_section_headers=True)

songs = (genius.search_artist('Kanye-west', max_songs=1, sort='popularity')).songs
s = [song.lyrics for song in songs]

print(s[0][-30:])

**Comment by annihilatorrrr** [comment]
Also in lyrics 
Can you give a temporary solution for this :

EmbedShare URLCopyEmbedCopy
At last line and at the starting : Searching for "****"...
Done.

**Comment by Vuizur** [comment]
Thanks for the regex, I had exactly the same problem.

I slightly modified the regex to
`hyperlinks_removed = re.sub(r"[0-9]*URLCopyEmbedCopy",'',lyrics)
`
because the other one failed for songs that had zero shares.

**Comment by emorevival** [comment]
I had to slightly modify Vuizur's solution because it was only getting the URLCopy part

(Javascript):
`let re = /[0-9].*URLCopyEmbedCopy/`
`lyrics.match(re)`

**Comment by crue-ton** [comment]
Thanks! I was wondering why the output on my songs lyrics were outputting this!
