### ISSUE TITLE
Throw custom error if song has no lyrics 

### ISSUE THREAD

**Issue by Rsalganik1123** [johnwmillr/LyricsGenius#227]
**Is your feature request related to a problem? Please describe.**
Given your current code version, I am unable to differentiate between songs that are in the Genius database but don't have lyrics (like classical music, etc) and songs that aren't in the database. This makes large-scale scraping with different types of music difficult. 

**Describe the solution you'd like**
Instead of just outputting an error message, I would like you to throw a custom error (which I can catch) when a song is in the db but not lyrical. 

**Describe alternatives you've considered**
Alternatively, I will have to find auxiliary dataset which includes genre and extrapolate whether the song isn't in DB of if the style of it is not lyrical. This is incredibly time consuming and not very accurate (given that even instrumental pieces have vocalizations even if they don't have explicit lyrics). 

**Additional context**
I'm sure I'm not the only one doing ML based music projects using your API. I love it, but sadly for this specific case, it's not performing the way I'd like. And if I feel this way, I'm sure other people will too. 

Cheers! Thanks for your wonderful work :)

**Comment by jmmelko** [comment]
I totally agree.

In my own version of the API, I have added the following lines in genius.py, around line 440:

```
song_info = result
 if not valid:
            if song_info.get('instrumental'):
                if self.verbose: print('Specified song is instrumental.')
                return '[Instrumental]'
            else:                
               if self.verbose: print('Specified song does not contain lyrics. Rejecting.')
               return None
```

If you don't want to mess with the code, you could also instantiate the API object with the option `skip_non_songs` set to `False`, but in that case you'll have to handle the result yourself
