### ISSUE TITLE
no album/year attributes for Song

### ISSUE THREAD

**Issue by C-Gian** [johnwmillr/LyricsGenius#233]
**Describe the bug**
The Git example show how to retrieve info like album of release date but it's not working giving `AttributeError: 'Song' object has no attribute 'year'`, same for album, I tried to get them from the dict but they are not there neither. 

**Expected behavior**
get the release date and album about a song

**To Reproduce**
use the api search_song(a, t) and then use .year, .album

`Command raised an exception: AttributeError: 'Song' object has no attribute 'year'`

**Version info**
 - 3.0.1
 - windows

**Additional context**
I read that the attributes works with the previous version of the package, but which one? I tried 2.00 but I got another error (object not subscribtable).

**Comment by RazyRo** [comment]
AttributeError: 'Track' object has no attribute 'title'
