### ISSUE TITLE
Related Songs showing up in Lyrics

### ISSUE THREAD

**Issue by nwanne56** [johnwmillr/LyricsGenius#240]
I tried grabbing a song, and found a section (within the lyrics) of related songs. This is probably closely related to issue #237.

```
song = genius.search_song("Hello", "Adele")
hellolyrics = song.lyrics
print(hellolyrics)
```

**Version info**
 - Package version: 3.0.1
 - OS: Windows 10

"Hello Lyrics[Verse 1] ... (Highs, highs, highs, highs, lows, lows, lows, lows)\nAnymore\n**Related SongsSend My Love (To Your New Lover)AdeleEasy On MeAdeleAs It WasHarry Styles**[Chorus]\nHello from the other side ..."

**Comment by hbtalha** [comment]
I just tested it and I couldn't reproduce it

**Comment by nwanne56** [comment]
You're right, just tried.
