### ISSUE TITLE
All download/progress lost, when crashing while running the genius.search_artist()-Function.

### ISSUE THREAD

**Issue by Tr33Bug** [johnwmillr/LyricsGenius#250]
**Describe the bug**
Write a clear and concise description of what the bug is.

**Expected behavior**
When the function crashes, I expect to get the fully downloaded lyric files for the artists, witch are completed to the state of crashing. 

**To Reproduce**
My Setup is: 
I want to download the top 50 lyrics from a list of 100 Artists. Often the function crashes for example at song 20 and all the progress for this artist is lost. After the crash, the return of the function is none.

**Version info**
 - Package version: 3.0.1
 - OS: macOS m1 (python 3.9)

**Additional context**
I have a workaround with a loop to repeat on crash and try every artist max. 10 times. Works for now, but not nice :) 

THX for the great library, by the way. Enjoy using it!

if you want to see my use in the project, look over to [https://github.com/Tr33Bug/ML-NLP-LyricsGen-Transformer](https://github.com/Tr33Bug/ML-NLP-LyricsGen-Transformer)

**Comment by RyanCaldwell360** [comment]
@Tr33Bug were you running into ``` requests.exceptions.Timeout: Request timed out ``` errors upon calls to ``` genius.search_artist ``` ? I'm creating a little program that is running into this issue, but not sure how to properly address it
