### ISSUE TITLE
Doc clarification search_artist vs artist_songs

### ISSUE THREAD

**Issue by dsm-72** [johnwmillr/LyricsGenius#253]
What is the difference between:

```
genius.search_artist(...)
```

and

```
genius.artist_songs(...)
```

**Describe the solution you'd like**
Clarification on this.

**Describe alternatives you've considered**
Write a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by allerter** [comment]
`genius.search_artist` is a convenience method that searches for an artist and returns an `Artist` object if it finds one. On the other hand, `genius.artist_songs` is an API method that returns an artist's songs as a list of dictionaries. You can refer to the docs reference for more info:
https://lyricsgenius.readthedocs.io/en/latest/reference
