### ISSUE TITLE
how to get the genre of a song?

### ISSUE THREAD

**Issue by Mohammad9760** [johnwmillr/LyricsGenius#255]
https://lyricsgenius.readthedocs.io/en/master/reference/types.html?highlight=song#song 
there's no attribute for knowing the genre of the song.
I want to know if there's a way I can extract genre information about a song.
thanks!

**Comment by allerter** [comment]
AFAIK, there is no way to get the genre of a song.

**Comment by allerter** [comment]
You can get the genres set for a song from the `tags` key if you get the song info from their WebAPI:

```python
genius = lyricsgenius.PublicAPI()

song = genius.song(1)["song"]
for tag in song["tags"]:
    print(tag["name"], sep=", ")
```

There is a chance this might raise a HTTP 403 error which is referenced in #220
