### ISSUE TITLE
Add option to get metadata of desired track

### ISSUE THREAD

**Issue by 808arc** [johnwmillr/LyricsGenius#257]
Firstly, I would like to extend my appreciation for the exceptional tool you have developed!

Could I ask you please to add a method that will return also who produced a track? (I highlighted area with blue color) 
If it will be able to implement with return of producer names and their link_pages on Genius.com, I will be kindly appreciated! 

Thank you for your attention to this matter and for creating such an impressive tool.

![telegram-cloud-photo-size-2-5400194413306692971-y](https://github.com/johnwmillr/LyricsGenius/assets/109691255/e6606c7b-ebed-4231-ad14-0030a412d94d)

**Comment by allerter** [comment]
You can get the producers of a song if you get the song info from their WebAPI:

```python
genius = lyricsgenius.PublicAPI()

song = genius.song(1)["song"]
for artist in song["producer_artists"]:
    print(artist["name"], sep=", ")
```

There is a chance this might raise a HTTP 403 error which is referenced in #220

**Comment by 808arc** [comment]
Thank you! Im trying to test this way ASAP

**Comment by 808arc** [comment]
Hey @allerter,

Just wanted to drop a quick note to say thanks for showing me a way to tackle my idea. I gave it a try, and it worked like a charm!

By the way, I have a small question. It seems that when I set max_songs=10, the code crashes. It only works smoothly if I keep the value at 2 or below.

Here's the code snippet I'm referring to:

```
genius = lyricsgenius.PublicAPI()

# Search for 10 Drake songs using the 'search_artist' method
artist = genius.search_artist("Drake", max_songs=1)

# Iterate over the songs
for song in artist.songs:
    # Retrieve the information of the song
    song_info = genius.song(song.id)

    # Iterate over the producer artists of the song
    for artist in song_info["song"]["producer_artists"]:
        print(artist["name"], sep=", ")
```

If you have any tips or insights on how to overcome this issue, I'd really appreciate your help.
Thanks again for your support!

**Comment by allerter** [comment]
That is likely because of the timeout errors. You could try increasing the sleep time between each request:

```python
genius = lyricsgenius.PublicAPI(sleep_time=2)
```
This way, the client waits 2 seconds between each request to the API.

**Comment by 808arc** [comment]
Hey @allerter, exciting news! I've fixed my code and now it's returning the exact data I need. I can easily grab the names of the production team members. But here's the deal: I'm now facing a challenge where I want to fetch the producer's Instagram link. Do you reckon it's possible to get it solely using this API? Or should I turn to other tools like the 'scrapy' library? My thought is to search for the producer's page on the Genius website and scrape it smoothly. Your thoughts on this would be highly appreciated!

**Comment by allerter** [comment]
Actually, the WebAPI already provides their Twitter and Instagram username. Try this:
```
genius = lyricsgenius.PublicAPI(sleep_time=2)
artist = geniust.artist(264329)["artist"]
print(artist["instagram_name"])
```

**Comment by 808arc** [comment]
Thank you, @allerter! It's really worked well on me! I will keep updating my code, because I feel I need to find first how to retrieve Genius Artist ID. In order to appreciate your time, does it possible to ask you where can I read more about work with WEB API?

**Comment by allerter** [comment]
The WebAPI is the API users use when browsing through the Genius's website. It has no documentation and isn't meant to be used by the developers. Genius has their own official Developer API, but it's very limited, so we resort to their unofficial WebAPI to get the info we want. You can explore the WebAPI by looking at the dictionary objects returned by the methods we use. We also have a [reference docs](https://lyricsgenius.readthedocs.io/en/master/reference/api.html#public-api) that we've tried to implement all the WebAPI endpoints in.
