### ISSUE TITLE
Doesn't return any matching songs

### ISSUE THREAD

**Issue by kexo1** [johnwmillr/LyricsGenius#258]
**Describe the bug**
I search for song by using search_song and inputting title of song in it, but i get completely different results 

**Expected behavior**
Return literally first thing that shows up??

**To Reproduce**
song = self.genius.search_song("Song name")

Include the error message associated with the bug.

**Version info**
 - Package version 3.0.1
 - OS: Windows 10

Why does it return such weird results? When i test it on site it gives me song lyrics i want

**Comment by allerter** [comment]
What exact search term are you using?
`genius.search_song` is a convenience method that searches for a song and gets its lyrics. You could search for the song yourself and get its lyrics using the [methods available](https://lyricsgenius.readthedocs.io/en/master/reference/genius.html)

**Comment by kexo1** [comment]
i'm using `Genius.search_song(title=None, artist='', song_id=None, get_full_info=True)`where i put name of song into `title`, that's all, and i get completely different results, when i search same song on site, i get the results i want

For example i input title 'Save your tears':
this is what i get as [result ](https://pastebin.com/X5YCD6aT)

There's not a single mention of song i searched for
