### ISSUE TITLE
R.E.M. returns Changing artist name to 'Don Toliver'

### ISSUE THREAD

**Issue by glepore70** [johnwmillr/LyricsGenius#263]
Searching for the band R.E.M. returns "Changing artist name to 'Don Toliver'" regardless of how I format the band name (the above is correct.) What is the correct syntax for finding this band?

Thanks.

**Comment by IT-gor** [comment]
I have the same issue: searching for the artist "AZ" returns artist name "Iggy Azalea", even though the allow_name_change is set to False. Any ideas?

**Comment by IT-gor** [comment]
Also have a look here (same issue):

https://github.com/johnwmillr/LyricsGenius/issues/118

Quote: Proposed solution
I think a way to fix this is to not return the top hit, but instead check all the hits for type and to see if the 'id' matches the artist_name

Bug fix:
https://github.com/johnwmillr/LyricsGenius/pull/123
