### ISSUE TITLE
Lyrics have unwanted data returned with them 

### ISSUE THREAD

**Issue by KevinDellatore** [johnwmillr/LyricsGenius#264]
**Describe the bug**
Lyrics are often returned with data that are definitely not intended to be, or at least expected to be returned. 
This unwanted data usually includes: 

- X contributors   (X is the number of contributors on the Genius page)
- [song] Lyrics   
- See [artist] LiveGet tickets as low as $<price>
- ,[song]Embed  

**Expected behavior**
The lyrics and only the lyrics would be returned without any extra useless data

**To Reproduce**
1. use the library to grab the lyrics from Genius
2. Return or print the lyrics 

- I was able to get this to repeatedly happen with almost all songs I've tried, but for the testing of my own application I've been using 3 songs: _A Grave Mistake_ by Ice Nine Kills, _Porcelain_ by Motionless in White, and _Not Afraid_ by Eminem.

There is no error message because there is no error, just a fault in how the library is grabbing the lyrics.

**Version info**
 - Package version: 3.0.1
 - OS: Windows 11

**Additional context**
I saw this problem was reported in issue 254 but since its several months old at this point, I didn't want to necro it. I'll try using the "solution" provided in that thread, but since this issue is seemingly unintended I wanted to make it known that its still happening. 

(Also, I'm fairly inexperienced at using GitHub as a whole, so if this has been solved in separate forks I apologize)

**Comment by joshp23** [comment]
This https://github.com/johnwmillr/LyricsGenius/pull/215#issuecomment-1399092335 will fix the garbage data issues
