### ISSUE TITLE
Step by step setup with "403 Client Error"

### ISSUE THREAD

**Issue by orlevit** [johnwmillr/LyricsGenius#270]
Hi 👋
I am folllowing the usage instructions and I get the following error:
_"HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=Andy+Shauf"_

**The code + error:**
![image](https://github.com/johnwmillr/LyricsGenius/assets/49340082/a4904d6f-3450-40f4-9f20-4d21e452447a)

**The token is the "generated access token" from the Genius API:**
![image](https://github.com/johnwmillr/LyricsGenius/assets/49340082/8f83aceb-ac57-46e4-9915-7275979ee42a)

**Even with oauth2, I still get the same error**
![image](https://github.com/johnwmillr/LyricsGenius/assets/49340082/b5e9b532-8429-4e4f-b6a6-c4edca4d2e25)

What am i missing?
Thanks for the help! 😊

**Comment by allerter** [comment]
Hi. You're not missing anything. Also, you don't need to set up OAuth2 unless you need it for authorizing people on your web app (which doesn't seem to be the case for you).
The problem here is that `geniust.search_artist` sends requests to Genius's Web API; this API is the front-facing API that doesn't need a token to be used and subsequently is checked by Genius's IP checker. The solution here is to either: change your IP or use methods that don't send requests to the Web API (you will have limited functionality in this case).

**Comment by orlevit** [comment]
Thanks! 
It worked 😊

**Comment by Louanes1** [comment]
It worked when I tried to run from a local python file. Same code wasn't working on google collab (not the same ip address) I was getting the 403 error code.

Sample code to get lyrics from a list of artists : 

`fields = ["title", "artist", "lyrics"]
token = os.environ["ACCESS_TOKEN_GENIUS"]
# Setup the Genius API with a token and specific settings to filter and format the lyrics
genius = lg.Genius(token, skip_non_songs=True,
                   excluded_terms=["(Remix)", "(Live)"],
                   remove_section_headers=True, verbose=False, retries=5)

# Define a function to retrieve lyrics for a list of artists
def get_lyrics(artists: list, max_songs: int, output_path: str, write_headers: bool):
    # Open the CSV file for appending data
    csvfile = open(output_path, "a")
    # Create a CSV DictWriter object to handle the writing of data
    writer = csv.DictWriter(csvfile, fieldnames=fields, restval='')
    
    # If specified, write the header row in the CSV file
    if write_headers:
        writer.writeheader()
    
    # Iterate over the list of artists to retrieve their songs
    for name in artists:
        try:
            # Search for the artist on Genius and get their songs
            songs = (genius.search_artist(name, max_songs=max_songs)).songs
            for c,song in enumerate(songs):
                print(f"Processing song... \n {song.artist} : {song.title} \n")
                try:
                    # Create a dictionary for the current song with the desired information
                    song_dict = {
                        "title": song.title,
                        "artist": song.artist,
                        # Clean up the lyrics by replacing new lines with colons and splitting by the word "Lyrics:"
                        "lyrics": song.lyrics.replace("\n", ":").split("Lyrics:")[1]
                    }
                    # Write the song's information to the CSV file
                    writer.writerow(song_dict)
                except Exception as e:
                    # If an exception occurs during the song data processing, print the exception
                    print(f"Exception at {name}: {c+1}, {str(e)}")
            # Print a success message for the artist once all their songs are processed
            print(f"-----------------{song.artist} SUCCESSFULLY ADDED-------------------- \n"
                  f"  SONG COUNT: {c}")
        except requests.exceptions.HTTPError as error:
            # Handle HTTP errors during the artist search
            print("HTTP Error")
            print(error.args[0])
    # Close the CSV file after writing is complete
    csvfile.close()`
