### ISSUE TITLE
Genre query early stopping

### ISSUE THREAD

**Issue by orlevit** [johnwmillr/LyricsGenius#271]
I am using the snippets in the docs: [link](https://lyricsgenius.readthedocs.io/en/master/examples/snippets.html) to get "Getting songs by tag (genre)":

```
# this gets the lyrics of all the songs that have the pop tag.
genius = Genius(token)
page = 1
lyrics = []
while page:
    res = genius.tag('pop', page=page)
    for hit in res['hits']:
        song_lyrics = genius.lyrics(song_url=hit['url'])
        lyrics.append(song_lyrics)
    page = res['next_page']
```

I am running this code with tag : "bachata" and noticed that one page is returning 19 results instead of 20:
![image](https://github.com/johnwmillr/LyricsGenius/assets/49340082/d2aecbae-956b-4c96-a7d9-195175ddae77)

In the source code : "res['next_page']" is None if the length of the hits not equals 20...
Is it a bug?

**Comment by allerter** [comment]
Full pages include 20 hits, indicating there might be a next page. If a page has fewer than 20, it means that there is no next page. It could be that Genius returns fewer than 20 even if there IS a next page, but that's just Genius being Genius.
