### ISSUE TITLE
Please update pip pocket

### ISSUE THREAD

**Issue by sega-gremlen** [johnwmillr/LyricsGenius#274]
I spent an hour trying to resolve the problem with removing extra data in the lyrics (like contributors, etc.). 
And now I see that the Git repository no longer has this issue. Please update the version available on pip.

**Comment by johnwmillr** [comment]
Hello @sega-gremlen, I've updated the [package on PyPI](https://pypi.org/project/lyricsgenius/) to the latest version (3.1.1). Thank you for your patience.
