### ISSUE TITLE
genius.search_song returns 403 Forbidden

### ISSUE THREAD

**Issue by QuentindiMeo** [johnwmillr/LyricsGenius#287]
I've been using the package for a couple of months now, but I started getting those like half an hour ago; not sure where it's originating from:

```
File ".../lyrics/genius.py", line 79, in getGeniusSong
    result = genius.search_song(song_title, artist_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/lyricsgenius/genius.py", line 402, in search_song
    search_response = self.search_all(search_term)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
    return self.search(search_term, per_page, page, endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
    return self._make_request(path, params_=params, public_api=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/base.py", line 88, in _make_request
    raise HTTPError(response.status_code, error) from e
requests.exceptions.HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=Hello+Adele
```

**Comment by ClaireCJS** [comment]
Came here to say this. I see it’s apparently a race and you beat me to it! :)

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Taking a look at this

`https://genius.com/api/search/multi?q` works fine outside of Python, so seems like something specifically in the package is somehow getting 403d

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
The User Agent is being blocked.

Verified this by commenting out the User-Agent in requests, and by using Bruno to make API requests.

**User-Agent Header enabled**
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/1da1410e-5601-4233-970f-c07c6aac52b2" />

**User-Agent Header disabled**
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/ab90d683-d1cb-4e87-b372-6db7ee201634" />

Removing that all together seems iffy, but I think UserAgents are supposed to be per user, so maybe it could be set each time the package runs?

**Comment by erdemunal35** [comment]
> I've been using the package for a couple of months now, but I started getting those like half an hour ago; not sure where it's originating from:
> 
> ```
> File ".../lyrics/genius.py", line 79, in getGeniusSong
>     result = genius.search_song(song_title, artist_name)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "~/.local/lib/python3.12/site-packages/lyricsgenius/genius.py", line 402, in search_song
>     search_response = self.search_all(search_term)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/public_methods/search.py", line 210, in search_all
>     return self.search(search_term, per_page, page, endpoint)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/public_methods/search.py", line 45, in search
>     return self._make_request(path, params_=params, public_api=True)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "~/.local/lib/python3.12/site-packages/lyricsgenius/api/base.py", line 88, in _make_request
>     raise HTTPError(response.status_code, error) from e
> requests.exceptions.HTTPError: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/api/search/multi?q=Hello+Adele
> ```

```
Error fetching lyrics for song ID 10951681: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/Twisted-sister-burn-in-hell-2024-remaster-lyrics
Error fetching lyrics for song ID 1713325: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/Twisted-sister-bad-boys-of-rock-n-roll-another-version-lyrics
Error fetching lyrics for song ID 1258681: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/Twisted-sister-cant-stand-still-lyrics
Error fetching lyrics for song ID 1055085: [Errno 403] 403 Client Error: Forbidden for url: https://genius.com/Twisted-sister-be-chrool-to-your-scuel-lyrics
...
```
getting the same error while using artist_songs() function

**Comment by likgaa** [comment]
I encountered the same problem when my assignment was about to reach deadline. 
![image](https://github.com/user-attachments/assets/8a862de3-dba3-4bcf-a7a1-a02a749707e3)

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Until the User Agent is changed, this issue will remain for all endpoints, I believe.  You can change it yourself (or remove it entirely) until there is an official fix.

**Comment by ClaireCJS** [comment]
can we change it ourselves if we just use the EXE file in a workflow?

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Yes, you should be able to download the repo and just edit the line.  You can also download the pull request I made, and it will already be fixed!
