### ISSUE TITLE
Enconding error during saving of lyrics for an artist

### ISSUE THREAD

**Issue by devspaceship** [johnwmillr/LyricsGenius#34]
I tried fetching the lyrics of the french rapper Nekfeu and saving them in txt format but I got that error
`Traceback
 (most recent call last):
  File "lyrics_fetch.py", line 6, in <module>
    artist.save_lyrics(format = "txt")
  File "D:\Anaconda3\lib\site-packages\lyricsgenius\artist.py", line 134, in save_lyrics
    lyrics_file.write(lyrics_to_write)
  File "D:\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 20121: character maps to <undefined>`

**Comment by johnwmillr** [comment]
Thanks for pointing this out. I thought I had addressed the Unicode bugs, but it looks like this will be an ongoing struggle...

Do you know which song gave you the error? I tried saving Nekfeu lyrics but only on two of his songs, "30 Septembre" and "7:77AM", and they saved without throwing an error.

**Comment by DevSpaceship** [comment]
Yeah encoding errors seems to be a pain in the ass, I also had a problem with another artist where it couldn't map ō so I decided to use an ugly but working solution for the moment, I simply replaced `lyrics_file.write(lyrics_to_write)` by `print(lyrics_to_write)` and copied and pasted from the console but I'll try to think about a solution ( `lyrics_file.write(lyrics_to_write.encode(encoding = 'utf-8', errors = 'ignore').decode(encoding = 'utf-8'))`  didn't work either)

**Comment by johnwmillr** [comment]
Hey @devspaceship, do you mind trying the same searches you were doing before with the latest version of the code? Or, could you send me the names of the artists you were searching for?

My latest PR (#49) isn't as aggressive with its decoding, and I'm curious whether that may help it avoid the same errors.

Thanks,
John

**Comment by JakeStanger** [comment]
I'm hoping #51 fixes this, seems to work for me.

**Comment by johnwmillr** [comment]
Closed by #51. The encoding issues are sure to crop up again in the future though...
