### ISSUE TITLE
Let the user pass a function to handle the verse, chorus (and other) tags

### ISSUE THREAD

**Issue by laurolima** [johnwmillr/LyricsGenius#35]
The artist tags in the middle of the lyrics may be very helpful, depending on the application. Maybe another solution is to pass the whole lyrics, with the [tags] unparsed.

**Comment by johnwmillr** [comment]
You’re right, this would be a helpful feature. The raw lyrics text should be available to the user. I’ll try to get around to a fix in the next few days, but feel free to open a pull request if you have time.

**Comment by johnwmillr** [comment]
Closed by PR #37
