### ISSUE TITLE
Lyrics only?

### ISSUE THREAD

**Issue by HandsomeDevilv112** [johnwmillr/LyricsGenius#40]
Is there a way to only pull down the lyrics?
I'm having to sort through the files to remove year/album/artist/etc, and I got to thinking that there just has to be a better way of doing it.

**Comment by johnwmillr** [comment]
There isn't a way to only return lyrics the way the code is currently written. But why don't you want to get the other information?

**Comment by HandsomeDevilv112** [comment]
I'm interested in making a lyrics generator to select rhyming and/or otherwise appropriate words/phrases.
I'll go ahead and close this issue. The only problem here is between the keyboard and chair.
