### ISSUE TITLE
Error while searching for all lyrics by Kanye West

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#43]
From a [comment](http://disq.us/p/1tnc084) on my blog:

> I'm looking to use it to analyze how an artist's lyrics change over different albums. My first thought was just to pull all of the artist's songs, but I believe there is a song in their directory with missing lyrics that is causing the search to quit.
>
> So is there either a.) a way to avoid the search from stopping or b.) a way to pull songs by album instead of by artist?

> I got the error when using the search function on Kanye West. The seach will run up to "All Falls Down" and it prints this AttributeError: 'NoneType' object has no attribute 'get_text' and stops. Looking on the website, the next song on his list of songs is "All Falls Down (Live)" and says it is "Missing Lyrics" so I assumed this caused the error.

So this probably has to do with calling the `get_text()` function when there aren't actually lyrics available.

**Comment by johnwmillr** [comment]
From a [new comment](http://disq.us/p/1u27tfv) on my blog:

> Hi John. I seem to be running into the same error as Elijah. I'm not sure if I'm doing something wrong (I'm quite new to Python and programming in general).
> 
> It happens with a few artists (for example, Kacey Musgraves, Kanye West, and Taylor Swift).
> 
> Here is my code:
> songs_by_artist = api.search_artist('Kacey Musgraves')
> 
> I get 4 songs, and then an error:
> Searching for songs by Kacey Musgraves...
> 
> Song 1: "Apologize (Acoustic Version)"
> Song 2: "Are You Sure"
> Song 3: "A Spoonful of Sugar (from "Mary Poppins")"
> "A Very Kacey Christmas [Tracklist + Album Cover]" does not contain lyrics. Rejecting.
> Song 4: "A Willie Nice Christmas"
> 
> File "C:\Users\Nick\Anaconda2\envs\Playground36TwentyEighteen\lib\site-packages\lyricsgenius\api.py", line 243, in search_artist
> lyrics = self._scrape_song_lyrics_from_url(json_song['url'], remove_section_headers)
> 
> File "C:\Users\Nick\Anaconda2\envs\Playground36TwentyEighteen\lib\site-packages\lyricsgenius\api.py", line 112, in _scrape_song_lyrics_from_url
> lyrics = html.find("div", class_="lyrics").get_text()
> 
> AttributeError: 'NoneType' object has no attribute 'get_text'

I thought this error might be due to using an old version of the package (because I don't run into the same error when running the search myself), but I didn't run into any errors when trying earlier versions either (0.5 and 0.2). Waiting to hear back what Python and `lyricsgenius` version the user is using.

**Comment by NickVance** [comment]
Hey. It's Nick, who reported the bug on your blog.

I took a look at the code and think I found the issue. There are times that a song is in json_search with a URL, but the URL is not valid. For example: https://genius.com/Taylor-swift-acting-like-a-boy-lyrics . The method _scrape_song_lyrics_from_url() then tries to do a .get_text() on class lyrics of the html, but that doesn't exist. 

I think the solution is to add another check somewhere in the process to see if the URL is valid and the lyrics exist. I found a quick solution that checks if the lyrics class exists on the URL --  the error doesn't happen and most of the songs are loaded like normal, and for URLs that don't exist the lyrics are a string that is just a space: " ". Of course this isn't ideal and there are better ways to solve it.

If it's alright with you, I'd like to try to solve the issue myself in the next few days. This is my first time working on a project on GitHub and on an open source project, so I think the experience of going through it could help me learn quite a bit of how these things work.

**Comment by johnwmillr** [comment]
Great catch! Go for it. Fork the repository then open a pull request back to mine when you’ve come up with a fix.

**Comment by nateraw** [comment]
Should this issue be closed? Is this solved?

**Comment by nateraw** [comment]
Worked for me.

![image](https://user-images.githubusercontent.com/32437151/45463867-1e6ee300-b6cb-11e8-985d-65a882b324d2.png)

**Comment by johnwmillr** [comment]
Wonderful! Thanks for giving it a try. I'll merge #52 (after fixing the conflicts) and close the issue.
