### ISSUE TITLE
It's not an issue, but..

### ISSUE THREAD

**Issue by ThatTonybo** [johnwmillr/LyricsGenius#54]
I got a little question here. Is there a node.js version of this, or can somebody convert it?

I'm making a project that gets lyrics, and this is **exactly** what I need - but it's Python :(

Thanks!

**Comment by johnwmillr** [comment]
Hi Tony,

I'm not familiar with any node.js packages, but I found a couple after a quick Google search:
 - [node-lyrics](https://www.npmjs.com/package/node-lyrics)
 - [lyrics-js](https://www.npmjs.com/package/lyrics-js)

I hope that helps!

Of course you could use this as an excuse to incorporate Python ;)

John

**Comment by ThatTonybo** [comment]
Cheers for the fast response! I'll take a look, thanks for linking them. Good work on this however, they're pretty cool. 👍
