### ISSUE TITLE
Write more tests

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#55]
There really need to be more unit tests for this package. Help wanted!

The package currently runs with continuous integration on [Travis-CI](https://travis-ci.org/johnwmillr/LyricsGenius).

**Comment by raunakdaga** [comment]
Hi, I'm new to Python. Do you have any idea what this error might mean? 

TypeError: 'NoneType' object is not subscriptable

**Comment by johnwmillr** [comment]
With #171 merged, now feels like a good time to consider this issue resolved. Thanks to @Allerter, we have numerous tests.
