### ISSUE TITLE
Is it possible to add a timeout parameter for api.search_song()?

### ISSUE THREAD

**Issue by momomozhang** [johnwmillr/LyricsGenius#60]
I'm scraping lyrics of a list of songs, got a Read Timed Out error. Is it possible to change timeout parameter from 5 to 30?

error message:
ReadTimeout: HTTPSConnectionPool(host='api.genius.com', port=443): Read timed out. (read timeout=5)

**Version info**
 - Package version: 0.9.5
 - OS: MacOS Mojave 10.14

**Comment by johnwmillr** [comment]
Hi there,

You should be able to set the `timeout` value when you create the instance of the `Genius` class:

```python
import lyricsgenius
api = lyricsgenius.Genius(api_key, timeout=30)
```

You can also change the timeout after the instance is created:
```python
api.timeout = 60
print(api.timeout)
```

Let me know if that works for you!

**Comment by johnwmillr** [comment]
I’m going to go ahead and close this issue. Please feel free to comment again if the problem hasn’t been resolved.
