### ISSUE TITLE
Is there a way to add a parameter to make the search_artist function return nothing if an artist is not found?

### ISSUE THREAD

**Issue by rishabhtagore** [johnwmillr/LyricsGenius#61]
Currently when running on Jupyter I get a dialogue box that gives me a suggestion for another artists. Is there a way to avoid this dialogue box and have the function return something like "not found"? I'm scraping hundreds of artists so dealing with the dialogue box is a bit difficult.

**Comment by rishabhtagore** [comment]
That worked! Thank you!

**Comment by johnwmillr** [comment]
Great!
