### ISSUE TITLE
Is there a way to just return a JSON object with save_lyrics and not actually download the file?

### ISSUE THREAD

**Issue by rishabhtagore** [johnwmillr/LyricsGenius#62]
**Is your feature request related to a problem? Please describe.**
Write a clear and concise description of what the problem is -- e.g. "I'm always frustrated when [...]"

**Describe the solution you'd like**
Write a clear and concise description of what you want to happen.

**Describe alternatives you've considered**
Write a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

**Comment by rishabhtagore** [comment]
It might speed it up.

**Comment by johnwmillr** [comment]
Could you be more specific with your question? What do you mean by "not actually download the file"?

**Comment by johnwmillr** [comment]
I'm going to go ahead and close the issue, but feel free to comment again if you'd like to follow up.
