### ISSUE TITLE
Add more usage examples and documentation

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#63]
**Is your feature request related to a problem? Please describe.**
Users aren't aware of what features are available in `lyricsgenius` and are requesting features that are already a part of the package.

**Describe the solution you'd like**
Add documentation to the `README` that includes examples for more use cases. Eventually it would be nice to have a dedicated [documentation site](https://medium.com/@richyap13/a-simple-tutorial-on-how-to-document-your-python-project-using-sphinx-and-rinohtype-177c22a15b5b).

**Comment by leblanchannah** [comment]
Hi John,

Are you still looking for someone to help out with this? I want to contribute but I am pretty unfamiliar with the overall workflow of contributing to projects on GitHub.

**Comment by johnwmillr** [comment]
Hi Hannah,

Help on this would be great! The documentation in general could be improved on this project.

There are two tasks you could tackle:
  1. (less work) Add clear documentation to each of the methods within the codebase. You'll need to examine each method and figure out 1) its purpose 2) the purpose of each input variable 3) the output. This [chunk of code](https://github.com/johnwmillr/LyricsGenius/blob/a168c455c55b0ecd4c6fc65fcdaa28ed76c147e8/lyricsgenius/api.py#L110-L148) gives an example of the style you should follow when adding (or updating old) documentation.
  2. (more work) It'd be great to have a standalone [readthedocs](https://readthedocs.org) page for this package. The (potentially) hard part of this process would be figuring out all the configuration involved. If you do step 1 first, you'll essentially be translating the code documentation into the `readthedocs` site. You can use [sphinx](http://www.sphinx-doc.org/en/master/) to generate the docs site.

Example documentation for other projects:
  - Tweepy [repo](https://github.com/tweepy/tweepy) & [doc site](https://tweepy.readthedocs.io/en/v3.5.0/)
  - Spotipy [repo](https://github.com/plamere/spotipy) & [doc site](https://spotipy.readthedocs.io/en/latest/)

As far as workflow:
  1. Fork this repository
  2. Create a `add-documentation` branch on your forked repo
  3. Add commits (with clear commit messages!) to that branch
  4. When you're happy with your changes, open a pull request to this original repository from your `add-documentation` branch

How does that all sound? Let me know if you have questions!

**Comment by leblanchannah** [comment]
Thanks! I will start out with 1.

**Comment by Allerter** [comment]
Should we close this since #153 was merged?

**Comment by johnwmillr** [comment]
Yes. More usage examples are always welcome, but #153 was sufficient to close this issue.
