### ISSUE TITLE
How to avoid "SKIPPING `song name` (already found in artist collection)"?

### ISSUE THREAD

**Issue by trevordavies095** [johnwmillr/LyricsGenius#66]
Hi, great wrapper!

I'm trying to grab all the Radiohead lyrics from Genius to do some analysis on them. When I try and save all the songs to the json file I get the message

> SKIPPING `song name` (already found in artist collection)

In my case it's 

> SKIPPING "Morning Bell/Amnesiac" (already found in artist collection)
> SKIPPING "Hunting Bears" (already found in artist collection)
> SKIPPING "Feral" (already found in artist collection)

How can I avoid this? I need the data for these three songs.

Thanks!

**Comment by johnwmillr** [comment]
I'm glad you like the wrapper!

Try setting the `skip_duplicates` flag to `False` when you call `save_lyrics()` on the `Artist` object:

```python
artist.save_lyrics(skip_duplicates=False)
```

Let me know if that works for you. I'm sorry there wasn't proper documentation in place for you to find this yourself!

**Comment by trevordavies095** [comment]
That did it! Thanks
