### ISSUE TITLE
Song titles and artist names need to be too exact when searching

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#67]
**Describe the bug**
Searching for a song by a given artist requires an input for both song name and artist title too close to the exact song title and artist name.

**Expected behavior**
Searching for "problems" by "jay z" should get the song "99 problems", but the search fails, even though the search works on Genius.com. Searching for "99 problems" without an artist argument does find the correct song.

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. `song = api.search_song("99 problems", "jay z")`
2. `song` is `None`, but it should have found the song.

**Additional context**
The `lyricsgenius` search should be just as flexible as the Genius.com search.

**Comment by johnwmillr** [comment]
Thanks for the example, @robot3498712. I'm adding fixes on the [improve search flexibility](https://github.com/johnwmillr/LyricsGenius/tree/improve-search-flexibility) branch.

**Comment by robot3498712** [comment]
Awesome, thanks @johnwmillr 
I confirm getting results now for my searches, so I'm out of issues for the time being.
Cheers!
