### ISSUE TITLE
Artist.save_lyrics failing

### ISSUE THREAD

**Issue by TwistedAsylumMC** [johnwmillr/LyricsGenius#71]
**Describe the bug**
Using the code ``artist.save_lyrics()`` I am given an error when running the script

**Expected behavior**
I expected the lyrics of a chosen song to be saved to a file

**To Reproduce**
Describe the steps required to reproduce the behavior.
Use the following code:
```python
import lyricsgenius as genius

api = genius.Genius("MY TOKEN") # Replaced my api token with "MY TOKEN"
artist = api.search_artist("Ariana Grande", max_songs=1)
song = api.search_song("thank u, next", artist.name)
artist.add_song(song)
artist.save_lyrics()
```

Include the error message associated with the bug.
```
Traceback (most recent call last):
  File "C:\Users\sebfa\PycharmProjects\TTS\main.py", line 8, in <module>
    artist.save_lyrics()
  File "C:\Users\sebfa\PycharmProjects\TTS\venv\lib\site-packages\lyricsgenius\artist.py", line 109, in save
_lyrics
    filename = "Lyrics_{}.{}".format(self.artist.replace(" ", ""), format_)
AttributeError: 'Artist' object has no attribute 'artist'
```
**Version info**
 - Package version: 1.0.0
 - OS: Windows 10

**Additional context**

**Comment by johnwmillr** [comment]
Ah, thanks for catching this bug! I *think* the fix is as changing `self.artist` to `self.name`. I'll try to make the fix and update the code tonight.

**Comment by robot3498712** [comment]
Hi, something appears being off still. Minimal script is failing: 

import lyricsgenius as genius
access_token = 'XXXX'
api = genius.Genius(access_token)
artist = api.search_artist("The Beatles", max_songs=3)
artist.save_lyrics(format_='json', filename='out.json')

------

.\python\lyrics>py -3 ./genius.py
Searching for songs by The Beatles...

Song 1: "12-Bar Original"
Song 2: "1822!"
"1 [Booklet]" is not valid. Skipping.
"20 Greatest Hits - Art and Tracklist" is not valid. Skipping.
Song 3: ""Abbey Road" side two"

Reached user-specified song limit (3).
Done. Found 3 songs.
Traceback (most recent call last):
  File "./genius.py", line 19, in <module>
    artist.save_lyrics(format_='json', filename='out.json')
  File "C:\Python3\lib\site-packages\lyricsgenius\artist.py", line 129, in save_lyrics
    lyrics_to_write['songs'][-1]['album'] = song.album
  File "C:\Python3\lib\site-packages\lyricsgenius\song.py", line 45, in album
    if 'album' in self._body and 'name' in self._body['album']:
TypeError: argument of type 'NoneType' is not iterable

.\python\lyrics>py -3 --version
Python 3.6.2

**Comment by johnwmillr** [comment]
Shoot, okay. I'll try to take another look in the next couple of days. Thanks for following up.

**Comment by johnwmillr** [comment]
@robot3498712 hopefully #75 fixes this bug for you. I was using a sloppy method of accessing elements within the Song object's self._body dictionary, causing an error when the requested field wasn't present in the dict. Let me know if you do run into any more bugs!

**Comment by robot3498712** [comment]
@johnwmillr Thank you, I can confirm issue is fixed. Cheers!
