### ISSUE TITLE
Song search needs titles check

### ISSUE THREAD

**Issue by johnwmillr** [johnwmillr/LyricsGenius#79]
**Describe the bug**
The `search_song` method doesn't check that it's returning the correct song.

**Expected behavior**
Searching for "99 problems" returns a Drake song, "All Me", instead of the expected "99 Problems" by Jay-Z.

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. song = api.search_song("99 problems")
2. `print(song)`

**Additional context**
I should probably add a check in to make sure we're not missing a search result that actually matches the song name.

**Comment by HotGiardiniera** [comment]
Hi John,

Figured I would help contribute with the PR above. Let me know if that is what you had in mind to fix this bug.

-Chris

**Comment by johnwmillr** [comment]
Thanks for the contribution, Chris! I'll try to get to your PR this weekend.
