### ISSUE TITLE
Can't find certain songs

### ISSUE THREAD

**Issue by bradydowling** [johnwmillr/LyricsGenius#81]
**Describe the bug**
When searching for certain songs, no songs are returned. Examples include:
- "Sunflower" by Post Malone and Swae Lee
- "The Glorious Five" by Logic

**Expected behavior**
Results should show for songs that are easily searchable using the genius.com UI.

**To Reproduce**
Describe the steps required to reproduce the behavior.
1. From the CLI, run the following command: `lyricsgenius song "Sunflower" "Post Malone"`

Error message associated with the bug:
```
Searching for "Sunflower" by Post Malone...
Could not find specified song. Check spelling?
Could not find specified song. Check spelling?
```

**Version info**
 - 1.0.2
 - OS: macOS

**Additional context**
Doesn't appear to be an issue with special characters or too many characters (in the song or artist).

**Comment by johnwmillr** [comment]
Hi Brady,

Try upgrading to the latest version of the package ([1.2.0](https://pypi.org/project/lyricsgenius/1.2.0/)). This "song not found" bug should have been fixed by commit [572966f](https://github.com/johnwmillr/LyricsGenius/commit/572966f79e2be44868cfcbaa5d8cdcfbd9147a08).

Let me know if the latest version doesn't work for you!

John

**Comment by bradydowling** [comment]
Weird, it actually did work for me after I updated to the latest version. Sounds like there could be something fishy going on for one of us.

**Comment by johnwmillr** [comment]
FYI, @bradydowling, I noticed this line [in your code](https://github.com/bradydowling/lyrically/blob/54ee0ddbc6cfd74a1e3c7576149b3837522706cd/index.py#L48):

```python
# Todo: Remove [Hook], [Verse 1], etc
```

You can automatically remove the section headers when searching for songs by using this flag:

```python
api = genius.Genius('genius_key', remove_section_headers=True)
```

A little clunky, but it works.
