### ISSUE TITLE
FileNotFoundError when saving song with a "/"

### ISSUE THREAD

**Issue by victoriahuynh** [johnwmillr/LyricsGenius#87]
I was trying to save all the lyrics for songs from an artist, but the save_lyrics() function stopped once it hit a song that has a "/" in the song title.

Here is the error message I received:
`FileNotFoundError: [Errno 2] No such file or directory: 'lyrics_arianagrande_blessed/rainbow.json'`

To reproduce: 
`artist_name = "{Ariana Grande}"` 
`artist = api.search_artist(artist_name)`  
`artist.save_lyrics()`

(The song is the 32nd song of hers pulled up.)

**Comment by victoriahuynh** [comment]
This appears to be an issue with all characters that are illegal in file names that pop up in song titles, such as '?' and '*'.

**Comment by johnwmillr** [comment]
Hi Victoria, thanks for finding this bug. I'm writing a PR now that should address this issue. Let me know if you still have errors when saving these files.
