### ISSUE TITLE
Get all available info from song

### ISSUE THREAD

**Issue by dtquandt** [johnwmillr/LyricsGenius#92]
Hey, I noticed in your endpoint issue that the info provided by Genius includes some stuff that isn't accessible through this (that I've seen):

    https://genius.com/api/artists/2/songs?page=5&sort=popularity

I mean things like 'pageviews' or 'header_image_url'.

How hard would it be to add a song.pageviews or song.headerimage, for instance? It could be useful for a few applications.

Also, and this is sort of related, what does get_full_info refer to, exactly? Year and such or more than that?

Thanks!

**Comment by johnwmillr** [comment]
Hi Daniel,

Sorry for taking so long to get back to you! Do you mean 'pageviews' and 'header_image_url' are values present on the page but not returned by the API? I'm reluctant to include additional calls to scrape the Genius page, but I suppose the data for the page is all present when the `get` request is made to the page during `_scrape_song_lyrics_from_url`. I'd be happy for a pull request that scrapes additional info from the _already requested_ HTML, but I don't want to make additional requests to Genius.com.

The `get_full_info` flag does in fact return (along with other data) the `header_image_url` value.

The `get_full_info` flag adds an extra API call that returns the same song object but with additional data fields (e.g. `writer_artists`, `featured_video`, `song_art_image_url`, etc.). You can play with th Genius API's [online interface](https://docs.genius.com) to see what all is returned in detail.

The extra data is mostly contained within `song._body`. I agree, it would be nice to have the extra fields within `_body` made into actual properties of the `Song` class. I'll put this into the backlog.

Does that clear the issue up for you?

**Comment by dtquandt** [comment]
Absolutely. I appreciate the thorough reply! The reason I asked is that I
am running some lyric analysis and I'm particularly interested in effects
on popularity, where pageviews would be an absolute indicator. Currently
all I have is artist position in the top 100 and song rank within each
artist thanks to popularity sorting.

Cheers!

**Comment by johnwmillr** [comment]
Yep, your best bet would be to look at the HTML that is already returned within the `_scrape_song_lyrics_from_url` method. Feel free to open another issue or PR if you have more questions. Good luck!
