### ISSUE TITLE
Compatibility with Scrapy

### ISSUE THREAD

**Issue by einstein6012** [johnwmillr/LyricsGenius#94]
**Is your feature request related to a problem? Please describe.**
Beautiful-soup is being used for the parsing of information from the API, it might be useful to add compatibility with the Scrapy package as it contains more power and functionality.

**Describe the solution you'd like**
An implementation alternative of the LyricsGenius using Scrapy

**Describe alternatives you've considered**
Using the wrapper to create Scrapy spiders, but this might be trickier

**Comment by johnwmillr** [comment]
Hi Joshua,

Thanks for your interest in the project! The project currently only uses `BeautifulSoup` for extracting lyrics from each song's webpage on Genius.com. Is there specific functionality you would like added with `Scrapy`?

As the project already performs as I'd like it to with `BeautifulSoup`, I won't add the `Scrapy` support; you're welcome to integrate `Scrapy` and open a PR though.

Cheers,
John

**Comment by johnwmillr** [comment]
I'm going to close this issue, but feel free to fork the repo and work on adding `Scrapy` compatibility.
