### ISSUE TITLE
Artist changed arbitrarily

### ISSUE THREAD

**Issue by Maristela-de-Jesus** [johnwmillr/LyricsGenius#96]
**Describe the bug**
In some instances the wrong artist is returned.

**Expected behavior**
The results should return the songs from the selected artists, instead sometimes the artist is changed.

**To Reproduce**
This is the code that I ran:
artist_rock_3 = api.search_artist(artists_rock[2],sort="popularity",max_songs=50)
print(artist_rock_3.songs)

For some artists I get this type of message:
Searching for songs by Queen...
Changing artist name to 'Beyoncé'

**Version info**
 - Package version: 1.4.0
 - OS: Windows 10 Pro

**Comment by johnwmillr** [comment]
Sorry this took so long to fix, @Maristela-de-Jesus! The bug should be resolved now. Thank you for opening the issue!
