### ISSUE TITLE
"'NoneType' object is not subscriptable" when requesting lyrics

### ISSUE THREAD

**Issue by seriousm4x** [johnwmillr/LyricsGenius#99]
**Describe the bug**
As soon as i request the lyrics from any song (via cli or python script), I get the `TypeError: 'NoneType' object is not subscriptable` error.

**Expected behavior**
Well, show me the lyrics

**To Reproduce**
1. install lyricsgenius
2. export the clientid to use it via cli
3. python -m lyricsgenius song "Rap God" "Eminem"
4. Throws error

```
λ python -m lyricsgenius song "Rap God" "Eminem"
Searching for "Rap God" by Eminem...
Traceback (most recent call last):
  File "C:\Users\max\scoop\apps\python\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\max\scoop\apps\python\current\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\max\scoop\apps\python\current\lib\site-packages\lyricsgenius\__main__.py", line 56, in <module>
    main()
  File "C:\Users\max\scoop\apps\python\current\lib\site-packages\lyricsgenius\__main__.py", line 36, in main
    song = api.search_song(*args.terms)
  File "C:\Users\max\scoop\apps\python\current\lib\site-packages\lyricsgenius\api.py", line 234, in search_song
    song_info.update(self.get_song(result['id'])['song'])
TypeError: 'NoneType' object is not subscriptable
```

**Version info**
 - Tried with version 1.5.1 as well as 1.5.2
 - OS: Windows 10
- Python 3.7.3 installed with scoop

**Comment by SwapnikKatkoori** [comment]
You need to export "Client Acess Token" not "Client ID". 
![2019-07-03_00-10-30](https://user-images.githubusercontent.com/40907690/60562860-447f7580-9d27-11e9-8cef-cc8736aa9050.jpeg)

**Comment by seriousm4x** [comment]
Yeah, sorry. I was using the correct one but said the wrong.
I fixed it. Problem was, that i was exporting the token wrong on windows cmd.

What i did:
`SET GENIUS_CLIENT_ACCESS_TOKEN="tokenhere"`
which is incorrect. It should be:
`SET GENIUS_CLIENT_ACCESS_TOKEN=tokenhere`

It´s working now...

**Comment by johnwmillr** [comment]
Thanks for your help, @SwapnikKatkoori. I'm glad it's working for you now, @seriousm4x. I should add a more descriptive error message that captures this missing access token.
